version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.2.2

jobs:
  example:
    docker:
      - image: openjdk:8-jdk-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch coverage.xml
      - run: |
          apk --no-cache add bash curl
      - run: |
          export CODACY_REPORTER_VERSION=latest
          export CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
          # comma separated list of report files
          # reference from https://stackoverflow.com/a/918931/7898052
          IFS=',' read -a report_array \<<EOF
          "coverage.xml"
          EOF
          
          params=''
          for report in "${report_array[@]}"
          do
              if [ ! -z "$report" ]
              then
                  params="$params -r $report"
              fi
          done

          if false; then
              skip_option="--skip"
          else
              skip_option=""
          fi

          bash <(curl -Ls https://coverage.codacy.com/get.sh) report $params --partial $skip_option &&\
          bash <(curl -Ls https://coverage.codacy.com/get.sh) final $skip_option

workflows:
  version: 2
  example:
    jobs:
      - example
