version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.2.2

jobs:
  example:
    docker:
      - image: ubuntu
        # openjdk:8-jdk-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch coverage.xml
      - run: |
          export CODACY_REPORTER_VERSION=latest
          export CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
          # comma separated list of report files
          # reference from https://unix.stackexchange.com/a/191125
          # plus https://stackoverflow.com/a/20323801/7898052
          report_array=$(printf "coverage.xml" | cut -d',' -f1)

          params=''
          for report in $report_array
          do
              if [ ! -z "$report" ]
              then
                  params="$params -r $report"
              fi
          done

          if false; then
            skip_option="--skip"
          else
            skip_option=""
          fi


          if [ -x "$(which curl)" ]; then
            curl -Ls https://coverage.codacy.com/get.sh > get.sh
          elif [ -x "$(which wget)" ] ; then
            wget -qO - https://coverage.codacy.com/get.sh > get.sh
          else
            printf "Could not find curl or wget, please install one."
          fi
          
          source get.sh report $params --partial $skip_option &&\
          source get.sh final $skip_option

workflows:
  version: 2
  example:
    jobs:
      - example
