version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.2.2

jobs:
  example:
    docker:
      - image: openjdk:8-jdk-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch coverage.xml
      - coverage-reporter/send_report:
          coverage-reports: 'coverage.xml'
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  version: 2
  example:
    jobs:
      - example
